//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Player/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""28179ff4-ba6d-4eef-a668-cd749e22b5da"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""183ca19d-88d1-49c8-8553-15a7080908d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeftRight"",
                    ""type"": ""Button"",
                    ""id"": ""30087a9b-cce3-4270-8646-7afe4e3a580f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveForwardBackward"",
                    ""type"": ""Button"",
                    ""id"": ""8b3e3a17-2c8c-4295-a4db-425f507b03d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pickup"",
                    ""type"": ""Button"",
                    ""id"": ""0c2b8020-1c93-47ad-a799-463f75f4d804"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryOpenClose"",
                    ""type"": ""Button"",
                    ""id"": ""40cb19e7-300a-4598-baf8-ca0377f627b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SplitItemByTwoParts"",
                    ""type"": ""Button"",
                    ""id"": ""0e8d0aba-66e1-447b-81e4-2a6230c7563c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateFirstItem"",
                    ""type"": ""Button"",
                    ""id"": ""3765facd-0929-4d1f-82a2-2aa09742235c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateSecondItem"",
                    ""type"": ""Button"",
                    ""id"": ""abeffc83-0418-46f4-9d38-506a4c2d45db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateThirdItem"",
                    ""type"": ""Button"",
                    ""id"": ""61dd8844-fa44-4843-a047-3ff663d7ac1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateFourthItem"",
                    ""type"": ""Button"",
                    ""id"": ""426223fc-05ab-4dd0-918d-9eab8dc3a354"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateFifthItem"",
                    ""type"": ""Button"",
                    ""id"": ""8077865a-4284-40f3-a9ac-2b81eeb22219"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateSixthItem"",
                    ""type"": ""Button"",
                    ""id"": ""ca595074-ad0a-4293-a560-d61dbc3a60dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateSeventhItem"",
                    ""type"": ""Button"",
                    ""id"": ""75a89365-c417-4939-a042-0d2a01808781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""faccd1b8-9552-4bb2-86f3-79be3a7a0ed2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""8f128e03-86ea-4456-b00a-bc4d9937e26b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""05b0d69d-cec3-48af-8252-526bb27fc447"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UltravioletStickUse"",
                    ""type"": ""Button"",
                    ""id"": ""702f1895-1245-442c-a6de-edb412e370cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopLookingOnObject"",
                    ""type"": ""Button"",
                    ""id"": ""1800a2d4-4a50-459d-babb-3cdafc03c0fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCloseSettings"",
                    ""type"": ""Button"",
                    ""id"": ""4092f053-574f-49e5-b87b-4364fdc01d16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenHelp"",
                    ""type"": ""Button"",
                    ""id"": ""8c8c22c2-4bb8-4a62-8a06-634ec93cf4da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9970d99f-65b2-47ea-8e50-24d45f2af37d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""431c994a-e633-4e1e-8ea7-eed7e3e02fb5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9c0b116d-6f7e-41b8-8901-f59beb9cff33"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""58406d22-c466-468c-85c8-f764d6c64fe2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ForwardBackward"",
                    ""id"": ""fc007c3b-49b4-4d1e-8655-9e2b814e1ef7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e2a4d554-5199-451b-8fa3-7344ab2acb99"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bf13b3e2-e8da-42e9-9d83-9905f5389689"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f5e0722b-a7c3-4f20-a525-db5ff155b791"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90050b3e-56b8-4818-b54b-3347256d02d4"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryOpenClose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef14066a-ec95-4a2c-b5c9-21554ce240db"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SplitItemByTwoParts"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30a0c8a9-07ed-4696-8b69-2ece2b60df95"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateFirstItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6df913bf-c3ce-44a8-a2d6-646215b23291"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateSecondItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9757b61-d2af-47a8-8817-21fb0a6c5a41"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateThirdItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5c27353-659d-4f08-858b-168a1e0ba258"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateFourthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cbbcd0d-045f-45a1-921a-92ded11d2fba"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateFifthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""159bbee1-5563-47d3-89e9-1aa4d53ca6c4"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateSixthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea3d1002-40f5-4dad-b634-6359bd2d7656"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateSeventhItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""590f5256-7422-4efc-84f8-f93b1a2364bb"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90d6e80a-dfe4-43ab-85c2-fba6f67d5b0b"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a1752e8-e758-4a5e-bab3-57c0ffba64b3"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84eb8b6f-bd36-428b-b15e-5e631ebb81e5"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UltravioletStickUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""033935a8-36ad-46c2-ba7e-0d1a302e05e2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopLookingOnObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5e19922-b1ee-4fee-9a2d-3b5e58f4e41f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCloseSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ec58f79-8ac3-4246-aa5d-a777ee1edd29"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenHelp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": []
        }
    ]
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Jump = m_Main.FindAction("Jump", throwIfNotFound: true);
        m_Main_MoveLeftRight = m_Main.FindAction("MoveLeftRight", throwIfNotFound: true);
        m_Main_MoveForwardBackward = m_Main.FindAction("MoveForwardBackward", throwIfNotFound: true);
        m_Main_Pickup = m_Main.FindAction("Pickup", throwIfNotFound: true);
        m_Main_InventoryOpenClose = m_Main.FindAction("InventoryOpenClose", throwIfNotFound: true);
        m_Main_SplitItemByTwoParts = m_Main.FindAction("SplitItemByTwoParts", throwIfNotFound: true);
        m_Main_ActivateFirstItem = m_Main.FindAction("ActivateFirstItem", throwIfNotFound: true);
        m_Main_ActivateSecondItem = m_Main.FindAction("ActivateSecondItem", throwIfNotFound: true);
        m_Main_ActivateThirdItem = m_Main.FindAction("ActivateThirdItem", throwIfNotFound: true);
        m_Main_ActivateFourthItem = m_Main.FindAction("ActivateFourthItem", throwIfNotFound: true);
        m_Main_ActivateFifthItem = m_Main.FindAction("ActivateFifthItem", throwIfNotFound: true);
        m_Main_ActivateSixthItem = m_Main.FindAction("ActivateSixthItem", throwIfNotFound: true);
        m_Main_ActivateSeventhItem = m_Main.FindAction("ActivateSeventhItem", throwIfNotFound: true);
        m_Main_Interact = m_Main.FindAction("Interact", throwIfNotFound: true);
        m_Main_Crouch = m_Main.FindAction("Crouch", throwIfNotFound: true);
        m_Main_Zoom = m_Main.FindAction("Zoom", throwIfNotFound: true);
        m_Main_UltravioletStickUse = m_Main.FindAction("UltravioletStickUse", throwIfNotFound: true);
        m_Main_StopLookingOnObject = m_Main.FindAction("StopLookingOnObject", throwIfNotFound: true);
        m_Main_OpenCloseSettings = m_Main.FindAction("OpenCloseSettings", throwIfNotFound: true);
        m_Main_OpenHelp = m_Main.FindAction("OpenHelp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_Jump;
    private readonly InputAction m_Main_MoveLeftRight;
    private readonly InputAction m_Main_MoveForwardBackward;
    private readonly InputAction m_Main_Pickup;
    private readonly InputAction m_Main_InventoryOpenClose;
    private readonly InputAction m_Main_SplitItemByTwoParts;
    private readonly InputAction m_Main_ActivateFirstItem;
    private readonly InputAction m_Main_ActivateSecondItem;
    private readonly InputAction m_Main_ActivateThirdItem;
    private readonly InputAction m_Main_ActivateFourthItem;
    private readonly InputAction m_Main_ActivateFifthItem;
    private readonly InputAction m_Main_ActivateSixthItem;
    private readonly InputAction m_Main_ActivateSeventhItem;
    private readonly InputAction m_Main_Interact;
    private readonly InputAction m_Main_Crouch;
    private readonly InputAction m_Main_Zoom;
    private readonly InputAction m_Main_UltravioletStickUse;
    private readonly InputAction m_Main_StopLookingOnObject;
    private readonly InputAction m_Main_OpenCloseSettings;
    private readonly InputAction m_Main_OpenHelp;
    public struct MainActions
    {
        private @PlayerControls m_Wrapper;
        public MainActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Main_Jump;
        public InputAction @MoveLeftRight => m_Wrapper.m_Main_MoveLeftRight;
        public InputAction @MoveForwardBackward => m_Wrapper.m_Main_MoveForwardBackward;
        public InputAction @Pickup => m_Wrapper.m_Main_Pickup;
        public InputAction @InventoryOpenClose => m_Wrapper.m_Main_InventoryOpenClose;
        public InputAction @SplitItemByTwoParts => m_Wrapper.m_Main_SplitItemByTwoParts;
        public InputAction @ActivateFirstItem => m_Wrapper.m_Main_ActivateFirstItem;
        public InputAction @ActivateSecondItem => m_Wrapper.m_Main_ActivateSecondItem;
        public InputAction @ActivateThirdItem => m_Wrapper.m_Main_ActivateThirdItem;
        public InputAction @ActivateFourthItem => m_Wrapper.m_Main_ActivateFourthItem;
        public InputAction @ActivateFifthItem => m_Wrapper.m_Main_ActivateFifthItem;
        public InputAction @ActivateSixthItem => m_Wrapper.m_Main_ActivateSixthItem;
        public InputAction @ActivateSeventhItem => m_Wrapper.m_Main_ActivateSeventhItem;
        public InputAction @Interact => m_Wrapper.m_Main_Interact;
        public InputAction @Crouch => m_Wrapper.m_Main_Crouch;
        public InputAction @Zoom => m_Wrapper.m_Main_Zoom;
        public InputAction @UltravioletStickUse => m_Wrapper.m_Main_UltravioletStickUse;
        public InputAction @StopLookingOnObject => m_Wrapper.m_Main_StopLookingOnObject;
        public InputAction @OpenCloseSettings => m_Wrapper.m_Main_OpenCloseSettings;
        public InputAction @OpenHelp => m_Wrapper.m_Main_OpenHelp;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @MoveLeftRight.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveLeftRight;
                @MoveForwardBackward.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveForwardBackward;
                @MoveForwardBackward.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveForwardBackward;
                @MoveForwardBackward.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveForwardBackward;
                @Pickup.started -= m_Wrapper.m_MainActionsCallbackInterface.OnPickup;
                @Pickup.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnPickup;
                @Pickup.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnPickup;
                @InventoryOpenClose.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryOpenClose;
                @InventoryOpenClose.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryOpenClose;
                @InventoryOpenClose.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryOpenClose;
                @SplitItemByTwoParts.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSplitItemByTwoParts;
                @ActivateFirstItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFirstItem;
                @ActivateFirstItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFirstItem;
                @ActivateFirstItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFirstItem;
                @ActivateSecondItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSecondItem;
                @ActivateSecondItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSecondItem;
                @ActivateSecondItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSecondItem;
                @ActivateThirdItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateThirdItem;
                @ActivateThirdItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateThirdItem;
                @ActivateThirdItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateThirdItem;
                @ActivateFourthItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFourthItem;
                @ActivateFourthItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFourthItem;
                @ActivateFourthItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFourthItem;
                @ActivateFifthItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFifthItem;
                @ActivateFifthItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFifthItem;
                @ActivateFifthItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFifthItem;
                @ActivateSixthItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSixthItem;
                @ActivateSixthItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSixthItem;
                @ActivateSixthItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSixthItem;
                @ActivateSeventhItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSeventhItem;
                @ActivateSeventhItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSeventhItem;
                @ActivateSeventhItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSeventhItem;
                @Interact.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Crouch.started -= m_Wrapper.m_MainActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnCrouch;
                @Zoom.started -= m_Wrapper.m_MainActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnZoom;
                @UltravioletStickUse.started -= m_Wrapper.m_MainActionsCallbackInterface.OnUltravioletStickUse;
                @UltravioletStickUse.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnUltravioletStickUse;
                @UltravioletStickUse.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnUltravioletStickUse;
                @StopLookingOnObject.started -= m_Wrapper.m_MainActionsCallbackInterface.OnStopLookingOnObject;
                @StopLookingOnObject.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnStopLookingOnObject;
                @StopLookingOnObject.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnStopLookingOnObject;
                @OpenCloseSettings.started -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenCloseSettings;
                @OpenCloseSettings.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenCloseSettings;
                @OpenCloseSettings.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenCloseSettings;
                @OpenHelp.started -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenHelp;
                @OpenHelp.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenHelp;
                @OpenHelp.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenHelp;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @MoveLeftRight.started += instance.OnMoveLeftRight;
                @MoveLeftRight.performed += instance.OnMoveLeftRight;
                @MoveLeftRight.canceled += instance.OnMoveLeftRight;
                @MoveForwardBackward.started += instance.OnMoveForwardBackward;
                @MoveForwardBackward.performed += instance.OnMoveForwardBackward;
                @MoveForwardBackward.canceled += instance.OnMoveForwardBackward;
                @Pickup.started += instance.OnPickup;
                @Pickup.performed += instance.OnPickup;
                @Pickup.canceled += instance.OnPickup;
                @InventoryOpenClose.started += instance.OnInventoryOpenClose;
                @InventoryOpenClose.performed += instance.OnInventoryOpenClose;
                @InventoryOpenClose.canceled += instance.OnInventoryOpenClose;
                @SplitItemByTwoParts.started += instance.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.performed += instance.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.canceled += instance.OnSplitItemByTwoParts;
                @ActivateFirstItem.started += instance.OnActivateFirstItem;
                @ActivateFirstItem.performed += instance.OnActivateFirstItem;
                @ActivateFirstItem.canceled += instance.OnActivateFirstItem;
                @ActivateSecondItem.started += instance.OnActivateSecondItem;
                @ActivateSecondItem.performed += instance.OnActivateSecondItem;
                @ActivateSecondItem.canceled += instance.OnActivateSecondItem;
                @ActivateThirdItem.started += instance.OnActivateThirdItem;
                @ActivateThirdItem.performed += instance.OnActivateThirdItem;
                @ActivateThirdItem.canceled += instance.OnActivateThirdItem;
                @ActivateFourthItem.started += instance.OnActivateFourthItem;
                @ActivateFourthItem.performed += instance.OnActivateFourthItem;
                @ActivateFourthItem.canceled += instance.OnActivateFourthItem;
                @ActivateFifthItem.started += instance.OnActivateFifthItem;
                @ActivateFifthItem.performed += instance.OnActivateFifthItem;
                @ActivateFifthItem.canceled += instance.OnActivateFifthItem;
                @ActivateSixthItem.started += instance.OnActivateSixthItem;
                @ActivateSixthItem.performed += instance.OnActivateSixthItem;
                @ActivateSixthItem.canceled += instance.OnActivateSixthItem;
                @ActivateSeventhItem.started += instance.OnActivateSeventhItem;
                @ActivateSeventhItem.performed += instance.OnActivateSeventhItem;
                @ActivateSeventhItem.canceled += instance.OnActivateSeventhItem;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @UltravioletStickUse.started += instance.OnUltravioletStickUse;
                @UltravioletStickUse.performed += instance.OnUltravioletStickUse;
                @UltravioletStickUse.canceled += instance.OnUltravioletStickUse;
                @StopLookingOnObject.started += instance.OnStopLookingOnObject;
                @StopLookingOnObject.performed += instance.OnStopLookingOnObject;
                @StopLookingOnObject.canceled += instance.OnStopLookingOnObject;
                @OpenCloseSettings.started += instance.OnOpenCloseSettings;
                @OpenCloseSettings.performed += instance.OnOpenCloseSettings;
                @OpenCloseSettings.canceled += instance.OnOpenCloseSettings;
                @OpenHelp.started += instance.OnOpenHelp;
                @OpenHelp.performed += instance.OnOpenHelp;
                @OpenHelp.canceled += instance.OnOpenHelp;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IMainActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMoveLeftRight(InputAction.CallbackContext context);
        void OnMoveForwardBackward(InputAction.CallbackContext context);
        void OnPickup(InputAction.CallbackContext context);
        void OnInventoryOpenClose(InputAction.CallbackContext context);
        void OnSplitItemByTwoParts(InputAction.CallbackContext context);
        void OnActivateFirstItem(InputAction.CallbackContext context);
        void OnActivateSecondItem(InputAction.CallbackContext context);
        void OnActivateThirdItem(InputAction.CallbackContext context);
        void OnActivateFourthItem(InputAction.CallbackContext context);
        void OnActivateFifthItem(InputAction.CallbackContext context);
        void OnActivateSixthItem(InputAction.CallbackContext context);
        void OnActivateSeventhItem(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnUltravioletStickUse(InputAction.CallbackContext context);
        void OnStopLookingOnObject(InputAction.CallbackContext context);
        void OnOpenCloseSettings(InputAction.CallbackContext context);
        void OnOpenHelp(InputAction.CallbackContext context);
    }
}
